//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('books')
export class booksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Author: string;

  @Column('text', { nullable: true })
  ISBN: string;

  @Column('date', { nullable: true })
  ReleaseDate: Date;

  @Column('text', { nullable: true })
  Description: string;

  @Column('bool', { nullable: true })
  AvailabilityStatus: boolean;

  @Column('date', { nullable: true })
  date1: Date;
}
