//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    books: {
      name: 'Books',
      fields: {
        Title: 'Title',
        Author: 'Author',
        ISBN: 'Isbn',
        ReleaseDate: 'Release Date',
        Description: 'Description',
        AvailabilityStatus: 'Availability Status',
        date1: 'Date1',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    books: {
      name: 'Books (fr)',
      fields: {
        Title: 'Title (fr)',
        Author: 'Author (fr)',
        ISBN: 'Isbn (fr)',
        ReleaseDate: 'Release Date (fr)',
        Description: 'Description (fr)',
        AvailabilityStatus: 'Availability Status (fr)',
        date1: 'Date1 (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
